name: Wired
version: '${project.version}'
main: me.austin.wired.Wired
api-version: 1.19
authors: [ Toast ]
commands:
  sethome:
    description: "Set a home"
  home:
    description: "Teleport to a home"
  death:
    description: "Teleport to your last death"
  grecipe:
    description: "get all recipes"
  getUUID:
    description: "get a player's UUID"
  vault:
    description: "get a player's vault balance"