name: Wired
version: '${project.version}'
main: me.toast.wired.Wired
api-version: 1.19
authors: [ Toast ]
commands:
  sethome:
    description: "Set a home"
  home:
    description: "Teleport to a home"
  death:
    description: "Teleport to your last death"
  grecipe:
    description: "get all recipes"
  vault:
    description: "get a player's vault balance"
  rEnchant:
    description: "Remove all enchants from your tool and get a book of them all."
  setMaxMana:
    description: "Set your max mana"
  setManaRegen:
    description: "Set your mana regen"
  giveSpell:
    description: "Give a spell to a player"
  gEnchant:
    description: "Give a custom enchant to a tool"
  upgrade:
    description: "Upgrade your character"
  Prestige:
    description: "Prestige your character"
  character:
    description: "View your character"